title: M. Lazer-Walker
email: em@lazerwalker.com
description: >
  I'm a Berlin-based game designer, conceptual artist, and software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.lazerwalker.com
twitter_username: lazerwalker
github_username:  lazerwalker

markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM

