# Site settings
title: Mike Lazer-Walker
email: mike@lazerwalker.com
description: >
  Mike is a New York-based game designer, conceptual artist, and software engineer.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: http://lazerwalker.com
twitter_username: lazerwalker
github_username:  lazerwalker

# Build settings
markdown: kramdown
