title: Em Lazer-Walker
email: blog@lazerwalker.com
description: >
  Em is a Toronto-based game designer, conceptual artist, and software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.lazerwalker.com
twitter_username: lazerwalker
github_username: lazerwalker

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-feed

collections:
  previews:
    output: true
    permalink: /previews/:slug/
